apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: node-label-operator
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    - job_name: 'node-label-operator'
      static_configs:
      - targets: ['node-label-operator-metrics:8080']
        labels:
          app: 'node-label-operator'
